Add docker-compose support for local dev
extragoodlabs/jumpwire pull request #28
Opened 2023-10-02 12:35 UTC by silvinobarreiros

- [ ] Add `docker-compose` file with postgres + jumpwire server
- [ ] Update `.gitignore`
- [ ] Update README

2023-10-02 22:22 UTC, hexedpackets requested changes
Nice addition to the setup. I left a few comments for some small changes.

2023-10-02 22:22 UTC, hexedpackets commented on README.md
> +### Using the Extragood Image
```suggestion
### Using the Docker Image
```

2023-10-02 22:22 UTC, hexedpackets commented on docker-compose.yml
> +      JUMPWIRE_ROOT_TOKEN: "Y1jhdxNJT6eGd6jofujl9MJeJc84XBiRpgIHPuY0Fgc="
I worry a bit about including default secrets, even just for local testing. Is there a good way to generate these for the YAML file instead?

2023-10-02 22:22 UTC, hexedpackets commented on README.md
> +We provide a bundle version of the proxy and a Postgres database using `docker-compose`. You can use your custom config or the one we provide.
```suggestion
We provide a bundled version of the proxy and a Postgres database using `docker-compose`. You can use your custom config or the one we provide.
```

2023-10-02 22:22 UTC, hexedpackets commented on README.md
> +### Docker
```suggestion
### Docker Compose
```

2023-10-02 22:22 UTC, hexedpackets commented on README.md
> +The `docker-compose.yaml` uses the local Dockerfile and will build a local instance from source. Use this for local development or to grab the
```suggestion
The `docker-compose.yml` uses the local Dockerfile and will build a local instance from source. Use this for local development or to grab the
```

2023-10-04 20:30 UTC, silvinobarreiros commented on docker-compose.yml
> +      JUMPWIRE_ROOT_TOKEN: "Y1jhdxNJT6eGd6jofujl9MJeJc84XBiRpgIHPuY0Fgc="
Yeah, I went back and forth here too. I figured it would be ok because it's just local testing and I wanted to make this super simple to get up and running.

We could create ENV vars and pass them in. That would make the `docker-compose` command a bit more tedious

2023-10-04 20:43 UTC, silvinobarreiros commented on jumpwire.yaml
> +# configure a postgresql database
Done. Moved to `priv/local/`

2023-10-04 20:44 UTC, silvinobarreiros commented on README.md
> +The `docker-compose.yaml` uses the local Dockerfile and will build a local instance from source. Use this for local development or to grab the
Not needed. I'll rename the file

2023-10-06 15:43 UTC, closed without merging